name: Deployment Periodic Healthcheck (full insurance coverage)

on:
  schedule:
    # UTC +0
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      url:
        description: "Ping target"
        required: true

jobs:
  health-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          # Check the following URLs one by one sequentially
          url: ${{ secrets.DEPLOYMENT_URL || inputs.url }}
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: false # Optional, defaults to "false"
          # Fail this action after this many failed attempts
          max-attempts: 3 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 10s # Optional, only applicable to max-attempts > 1
          # Retry all errors, including 404. This option might trigger curl upgrade.
          retry-all: false # Optional, defaults to "false"
          # String representation of cookie attached to health check request.
          # Format: `Name=Value`
          # cookie: "token=asdf1234" # Optional, default is empty
          # Basic auth login password pair.
          # Format: `login:password`
          # basic-auth: "login:password" # Optional, default is empty