name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

# job level if: is evaluated before env. SO NO...
# env:
#   IS_MAIN_PUSH: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

jobs:
  CI:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-24.04
    steps:
      # Cleanliness is ALL
      - name: Checkout tree
        uses: actions/checkout@v4
      
      - name: Env setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install

      # npm init playwright@latest is for proj scaffolding + browser + os dep
      - name: Install Playwright Browsers
        # this is just for browser + os deps
        run: npx playwright install --with-deps

      # formats
      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      # unit tests
      - name: Run tests
        run: npm test

      # e2e tests
      - name: Run Playwright tests
        run: npm run test:e2e
        
      # Output test report
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deployment:
    if: >
      ${{ 
        github.event_name == 'push' && github.ref == 'refs/heads/main' && 
        !contains(
          join(toJson(github.event.commits.*.message), ' '), 
          '#skip'
        ) 
      }}
    runs-on: ubuntu-24.04
    steps:
      # print out some git related stuff
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT" ${{ toJson(github.event.commits.*.message) }}
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"

      # Deploy to Render
      - name: Trigger deployment
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
  
  tag_release:
    needs: [deployment]
    if: >
      ${{ 
        !contains(
          join(toJson(github.event.commits.*.message), ' '), 
          '#skip'
        ) 
      }}
    # if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      # Checkout is needed for each job scope! -> no sharing fs
      - name: Checkout tree
        uses: actions/checkout@v4

      # Versioning
      - name: Bump version and push tag
        # safer with hash (1.75.0) cuz tags could be moving targets
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 11.14.0
