name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:

  CI:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-24.04
    steps:
      # Cleanliness is ALL
      - name: Checkout tree
        uses: actions/checkout@v4
      
      - name: Env setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install

      # npm init playwright@latest is for proj scaffolding + browser + os dep
      - name: Install Playwright Browsers
        # this is just for browser + os deps
        run: npx playwright install --with-deps

      # formats
      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      # unit tests
      - name: Run tests
        run: npm test

      # e2e tests
      - name: Run Playwright tests
        run: npm run test:e2e
        
      # Output test report
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deployment:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Trigger deployment
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
        