name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

# job level if: is evaluated before env. SO NO...
# env:
#   IS_MAIN_PUSH: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

jobs:
  CI:
    if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.title, '#no-ci') }}
    runs-on: ubuntu-24.04
    steps:
      # Cleanliness is ALL
      - name: Checkout tree
        uses: actions/checkout@v4
      
      - name: Env setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install

      # npm init playwright@latest is for proj scaffolding + browser + os dep
      - name: Install Playwright Browsers
        # this is just for browser + os deps
        run: npx playwright install --with-deps

      # formats
      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      # unit tests
      - name: Run tests
        run: npm test

      # e2e tests
      - name: Run Playwright tests
        run: npm run test:e2e
        
      # Output test report
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deployment:
    if: >
      ${{ 
        github.event_name == 'push' && github.ref == 'refs/heads/main' && 
        !contains(
          join(toJson(github.event.commits.*.message), ' '), 
          '#skip'
        ) 
      }}
    runs-on: ubuntu-24.04
    steps:
      - name: Faile fast for hook test
        run: exit 1
      # Deploy to Render
      - name: Trigger deployment
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
  
  tag_release:
    needs: [deployment]
    if: >
      ${{ 
        !contains(
          join(toJson(github.event.commits.*.message), ' '), 
          '#skip'
        ) 
      }}
    # if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      # Checkout is needed for each job scope! -> no sharing fs
      - name: Checkout tree
        uses: actions/checkout@v4

      # Versioning
      - name: Bump version and push tag
        # safer with hash (1.75.0) cuz tags could be moving targets
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 11.18.0

  notify:
    runs-on: ubuntu-24.04
    needs: [deployment]
    if: ${{ always() }}
    steps:
      - name: notify on deployment success
        if: ${{ needs.deployment.result == 'success' }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{
              "username": "Pikku Myy",
              "avatar_url": "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%2Fid%2FOIP.7SAFV037V1-ezvkAhffIWgHaHa%3Fpid%3DApi&f=1&ipt=f93d9e58395bec6151fbecf4165b5556a514a4aef44fc9ece95da62773c178bf&ipo=images",
              "embeds": [
                {
                  "title": "Successfully deployed!",
                  "description": "to [markdown test](https://some.url) by **someone**",
                  "color": 65280,
                  "fields": [
                    { "name": "Status", "value": "✅", "inline": true },
                    { "name": "Repository", "value": "${{ github.repository }}", "inline": true }
                  ],
                  "footer": { "text": "Severity: Info" }
                }
              ]
            }' \
            ${{ secrets.DISCORD_WEBHOOK }}

      - name: notify on deployment failure
        if: ${{ needs.deployment.result == 'failure' }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{
              "username": "Pikku Myy",
              "avatar_url": "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%2Fid%2FOIP.7SAFV037V1-ezvkAhffIWgHaHa%3Fpid%3DApi&f=1&ipt=f93d9e58395bec6151fbecf4165b5556a514a4aef44fc9ece95da62773c178bf&ipo=images",
              "embeds": [
                {
                  "title": "Deployment failed!",
                  "description": "Check [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for the run result",
                  "color": 16711680,
                  "fields": [
                    { "name": "Status", "value": "❌", "inline": true },
                    { "name": "Repository", "value": "${{ github.repository }}", "inline": true }
                  ],
                  "footer": { "text": "Severity: Error" }
                }
              ]
            }' \
            ${{ secrets.DISCORD_WEBHOOK }}

      # THE APP DON'T RECOGNIZE THE WEBHOOK URL
      # - name: notify on tag_release failure
      #   uses: rjstone/discord-webhook-notify@v2
      #   if: ${{ needs.tag_release.result == 'failure' }}
      #   with:
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      #     username: Pikku Myy
      #     avatarUrl: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%2Fid%2FOIP.7SAFV037V1-ezvkAhffIWgHaHa%3Fpid%3DApi&f=1&ipt=f93d9e58395bec6151fbecf4165b5556a514a4aef44fc9ece95da62773c178bf&ipo=images
      #     text: Tag was not released!
      #     flags: SuppressNotifications
      #     severity: warn
      #     color: '#ffa500'
      #     title: Tag was not released!
      #     description: "Check [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for the run result"